angular.module("dresscode",["ngRoute"])
.config(function($routeProvider){
  $routeProvider
  .when("/",{
    template:"<h1>asdasdas</h1>",
    controller:"loginController"
  })
  .when("/a",{
    template:"<h4>dfgsdd</h4>",
    controller:"a"
  });
});
